ci(codeql): remove on:push
Resolves the following error:

```
Error: Workflows triggered by Dependabot on the "push" event run
with read-only access. Uploading Code Scanning results requires
write access. To use Code Scanning with Dependabot, please ensure
you are using the "pull_request" event for this workflow and avoid
triggering on the "push" event for Dependabot branches. (...)
```